#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the editor syntax files from the word lists in upsil/keywords.py.

    python3 tools/gen_syntax.py           write the files
    python3 tools/gen_syntax.py --check   exit 1 if a file is out of date

Outputs:
    vscode-upsil/syntaxes/upsil.tmLanguage.json   VS Code / TextMate grammar
    editor/upsil.lang                             GtkSourceView (GNOME Text Editor, gedit)
    editor/upsil.xml                              KSyntaxHighlighting (Kate, KWrite, KDevelop)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Callable, Dict, Iterable, List
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from upsil import __version__  # noqa: E402
from upsil import keywords as kw  # noqa: E402

GENERATED = "Generated by tools/gen_syntax.py from upsil/keywords.py; do not edit by hand."

DECLARATIONS = tuple(w for w in kw.DECLARATION if w not in ("import", "as"))
IMPORT_WORDS = ("import", "as")
BOOLEANS = ("true", "false")
CONTEXTUAL_DECL = ("model", "graph", "llm", "vector_store")

ESCAPE_RE = r"""\\(?:[ntr0"'\\{}]|u[0-9a-fA-F]{4}|u\{[0-9a-fA-F]{1,6}\})"""
NUMBER_RES = (
    ("hex", r"\b0[xX][0-9a-fA-F](?:_?[0-9a-fA-F])*\b"),
    ("binary", r"\b0[bB][01](?:_?[01])*\b"),
    ("octal", r"\b0[oO][0-7](?:_?[0-7])*\b"),
    ("decimal", r"\b[0-9](?:_?[0-9])*(?:\.[0-9](?:_?[0-9])*)?(?:[eE][+-]?[0-9](?:_?[0-9])*)?\b"),
)
OPERATOR_RE = r"=>|->|\.\.=?|\*\*|[-+*/%@<>=!]=?"
TQ = '"' * 3


def words(items: Iterable[str]) -> str:
    return "|".join(items)


# ---------------------------------------------------------------------- TextMate (VS Code)

def textmate() -> str:
    ident = r"[\p{L}_][\p{L}\p{N}_]*"
    grammar = {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "comment": GENERATED,
        "name": "UpsiL",
        "scopeName": "source.upsil",
        "fileTypes": ["upl"],
        "patterns": [{"include": f"#{name}"} for name in
                     ("comments", "strings", "numbers", "declarations", "keywords", "constants",
                      "prompt", "operators", "builtins", "calls")],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.block.upsil", "begin": r"/\*", "end": r"\*/",
                 "patterns": [{"include": "#comments"}]},
                {"name": "comment.line.double-slash.upsil", "match": "//.*$"},
            ]},
            "strings": {"patterns": [
                {"name": "string.quoted.raw.triple.upsil", "begin": 'r"""', "end": '"""'},
                {"name": "string.quoted.raw.upsil", "begin": 'r"', "end": '"|$'},
                {"name": "string.quoted.triple.upsil", "begin": '"""', "end": '"""',
                 "patterns": [{"include": "#escapes"}, {"include": "#interpolation"}]},
                {"name": "string.quoted.double.upsil", "begin": '"', "end": '"|$',
                 "patterns": [{"include": "#escapes"}, {"include": "#interpolation"}]},
            ]},
            "escapes": {"name": "constant.character.escape.upsil", "match": ESCAPE_RE},
            "interpolation": {
                "name": "meta.interpolation.upsil",
                "begin": r"\{", "end": r"\}",
                "beginCaptures": {"0": {"name": "punctuation.section.interpolation.begin.upsil"}},
                "endCaptures": {"0": {"name": "punctuation.section.interpolation.end.upsil"}},
                "contentName": "meta.embedded.expression.upsil",
                "patterns": [{"include": "$self"}],
            },
            "numbers": {"patterns": [{"name": f"constant.numeric.{name}.upsil", "match": rx}
                                     for name, rx in NUMBER_RES]},
            "declarations": {"patterns": [
                {"match": rf"\b(fun|graph)\s+({ident})",
                 "captures": {"1": {"name": "storage.type.function.upsil"},
                              "2": {"name": "entity.name.function.upsil"}}},
                {"match": rf"\b(class|model)\s+({ident})",
                 "captures": {"1": {"name": "storage.type.class.upsil"},
                              "2": {"name": "entity.name.type.class.upsil"}}},
                {"match": rf"\b(llm|vector_store)(?=\s+{ident})",
                 "captures": {"1": {"name": "storage.type.resource.upsil"}}},
                {"match": r'\b(import)\s+(py)(?=\s*")',
                 "captures": {"1": {"name": "keyword.control.import.upsil"},
                              "2": {"name": "keyword.other.py.upsil"}}},
            ]},
            "keywords": {"patterns": [
                {"name": "keyword.control.upsil", "match": rf"\b({words(kw.CONTROL)})\b"},
                {"name": "storage.type.upsil", "match": rf"\b({words(DECLARATIONS)})\b"},
                {"name": "keyword.control.import.upsil", "match": rf"\b({words(IMPORT_WORDS)})\b"},
                {"name": "keyword.operator.word.upsil", "match": rf"\b({words(kw.OPERATOR_WORDS)})\b"},
            ]},
            "constants": {"patterns": [
                {"name": "constant.language.boolean.upsil", "match": rf"\b({words(BOOLEANS)})\b"},
                {"name": "constant.language.null.upsil", "match": r"\bnull\b"},
                {"name": "variable.language.self.upsil", "match": rf"\b({words(kw.SPECIAL_NAMES)})\b"},
            ]},
            "prompt": {"patterns": [
                {"name": "keyword.operator.prompt.upsil", "match": "=>"},
                {"match": r"(->)\s*(json)\b",
                 "captures": {"1": {"name": "keyword.operator.arrow.upsil"},
                              "2": {"name": "support.type.json.upsil"}}},
            ]},
            "operators": {"patterns": [
                {"name": "keyword.operator.arrow.upsil", "match": "->"},
                {"name": "keyword.operator.range.upsil", "match": r"\.\.=?"},
                {"name": "keyword.operator.comparison.upsil", "match": "==|!=|<=|>=|<|>"},
                {"name": "keyword.operator.assignment.upsil", "match": "[-+*/%]?="},
                {"name": "keyword.operator.arithmetic.upsil", "match": r"\*\*|[-+*/%@]"},
            ]},
            "builtins": {"name": "support.function.builtin.upsil",
                         "match": rf"\b({words(kw.BUILTINS)})\b(?=\s*\()"},
            "calls": {"match": rf"\b({ident})\s*(?=\()",
                      "captures": {"1": {"name": "entity.name.function.call.upsil"}}},
        },
    }
    return json.dumps(grammar, ensure_ascii=False, indent=2) + "\n"


# ---------------------------------------------------------------------- GtkSourceView

def _keywords_xml(items: Iterable[str], indent: str = "      ") -> str:
    return "\n".join(f"{indent}<keyword>{escape(w)}</keyword>" for w in items)


def gtksourceview() -> str:
    number = "|".join(rx for _, rx in NUMBER_RES).replace("(?:", "(")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- {GENERATED} -->
<!-- UpsiL {__version__}. Install: cp upsil.lang ~/.local/share/gtksourceview-5/language-specs/
     (gtksourceview-4 for gedit 40 and older). -->
<language id="upsil" name="UpsiL" version="2.0" _section="Source">
  <metadata>
    <property name="mimetypes">text/x-upsil</property>
    <property name="globs">*.upl</property>
    <property name="line-comment-start">//</property>
    <property name="block-comment-start">/*</property>
    <property name="block-comment-end">*/</property>
  </metadata>

  <styles>
    <style id="comment" name="Comment" map-to="def:comment"/>
    <style id="string" name="String" map-to="def:string"/>
    <style id="escape" name="Escaped Character" map-to="def:special-char"/>
    <style id="interpolation" name="Interpolation" map-to="def:special-char"/>
    <style id="keyword" name="Keyword" map-to="def:keyword"/>
    <style id="declaration" name="Declaration" map-to="def:keyword"/>
    <style id="operator" name="Operator" map-to="def:operator"/>
    <style id="boolean" name="Boolean" map-to="def:boolean"/>
    <style id="null" name="Null" map-to="def:special-constant"/>
    <style id="self" name="Self" map-to="def:builtin"/>
    <style id="builtin" name="Builtin Function" map-to="def:builtin"/>
    <style id="number" name="Number" map-to="def:number"/>
  </styles>

  <definitions>
    <context id="escape" style-ref="escape">
      <match>{escape(ESCAPE_RE.replace("(?:", "("))}</match>
    </context>

    <context id="interpolation">
      <start>\\{{</start>
      <end>\\}}</end>
      <include>
        <context sub-pattern="0" where="start" style-ref="interpolation"/>
        <context sub-pattern="0" where="end" style-ref="interpolation"/>
        <context ref="expression"/>
      </include>
    </context>

    <context id="raw-triple-string" style-ref="string" class="string" class-disabled="no-spell-check">
      <start>r{TQ}</start>
      <end>{TQ}</end>
    </context>

    <context id="raw-string" style-ref="string" end-at-line-end="true" class="string" class-disabled="no-spell-check">
      <start>r"</start>
      <end>"</end>
    </context>

    <context id="triple-string" style-ref="string" class="string" class-disabled="no-spell-check">
      <start>{TQ}</start>
      <end>{TQ}</end>
      <include>
        <context ref="escape"/>
        <context ref="interpolation"/>
      </include>
    </context>

    <context id="string" style-ref="string" end-at-line-end="true" class="string" class-disabled="no-spell-check">
      <start>"</start>
      <end>"</end>
      <include>
        <context ref="escape"/>
        <context ref="interpolation"/>
      </include>
    </context>

    <context id="line-comment" style-ref="comment" end-at-line-end="true" class="comment" class-disabled="no-spell-check">
      <start>//</start>
      <include>
        <context ref="def:in-comment"/>
      </include>
    </context>

    <context id="block-comment" style-ref="comment" class="comment" class-disabled="no-spell-check">
      <start>/\\*</start>
      <end>\\*/</end>
      <include>
        <context ref="def:in-comment"/>
        <context ref="block-comment"/>
      </include>
    </context>

    <context id="control" style-ref="keyword">
{_keywords_xml(kw.CONTROL)}
    </context>

    <context id="declarations" style-ref="declaration">
{_keywords_xml(kw.DECLARATION)}
    </context>

    <context id="contextual-declarations" style-ref="declaration">
      <match>\\%[({words(CONTEXTUAL_DECL)})(?=\\s+[[:alpha:]_])</match>
    </context>

    <context id="operator-words" style-ref="operator">
{_keywords_xml(kw.OPERATOR_WORDS)}
    </context>

    <context id="booleans" style-ref="boolean">
{_keywords_xml(BOOLEANS)}
    </context>

    <context id="null" style-ref="null">
      <keyword>null</keyword>
    </context>

    <context id="self" style-ref="self">
{_keywords_xml(kw.SPECIAL_NAMES)}
    </context>

    <context id="builtins" style-ref="builtin">
      <suffix>\\%](?=\\s*\\()</suffix>
{_keywords_xml(kw.BUILTINS)}
    </context>

    <context id="number" style-ref="number">
      <match>{escape(number)}</match>
    </context>

    <context id="operators" style-ref="operator">
      <match>{escape(OPERATOR_RE)}</match>
    </context>

    <context id="expression">
      <include>
        <context ref="raw-triple-string"/>
        <context ref="raw-string"/>
        <context ref="triple-string"/>
        <context ref="string"/>
        <context ref="number"/>
        <context ref="control"/>
        <context ref="declarations"/>
        <context ref="contextual-declarations"/>
        <context ref="operator-words"/>
        <context ref="booleans"/>
        <context ref="null"/>
        <context ref="self"/>
        <context ref="builtins"/>
        <context ref="operators"/>
      </include>
    </context>

    <context id="upsil" class="no-spell-check">
      <include>
        <context ref="line-comment"/>
        <context ref="block-comment"/>
        <context ref="expression"/>
      </include>
    </context>
  </definitions>
</language>
"""


# ---------------------------------------------------------------------- KSyntaxHighlighting

def _items_xml(items: Iterable[str], indent: str = "      ") -> str:
    return "\n".join(f"{indent}<item>{escape(w)}</item>" for w in items)


def ksyntax() -> str:
    number = "|".join(rx for _, rx in NUMBER_RES).replace("(?:", "(")
    escape_rule = escape(ESCAPE_RE.replace("(?:", "("), {'"': "&quot;"})
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- {GENERATED} -->
<!-- UpsiL {__version__}. Install: cp upsil.xml ~/.local/share/org.kde.syntax-highlighting/syntax/ -->
<language name="UpsiL" section="Sources" version="1" kateversion="5.0" extensions="*.upl"
          mimetype="text/x-upsil" indenter="cstyle" author="UpsiL contributors" license="Apache-2.0">
  <highlighting>
    <list name="control">
{_items_xml(kw.CONTROL)}
    </list>
    <list name="declarations">
{_items_xml(kw.DECLARATION)}
    </list>
    <list name="operator-words">
{_items_xml(kw.OPERATOR_WORDS)}
    </list>
    <list name="constants">
{_items_xml(kw.CONSTANTS)}
    </list>
    <list name="special">
{_items_xml(kw.SPECIAL_NAMES)}
    </list>
    <list name="builtins">
{_items_xml(kw.BUILTINS)}
    </list>
    <contexts>
      <context name="Normal" attribute="Normal Text" lineEndContext="#stay">
        <DetectSpaces/>
        <Detect2Chars attribute="Comment" context="LineComment" char="/" char1="/"/>
        <Detect2Chars attribute="Comment" context="BlockComment" char="/" char1="*" beginRegion="Comment"/>
        <StringDetect attribute="String" context="RawTripleString" String="r&quot;&quot;&quot;"/>
        <Detect2Chars attribute="String" context="RawString" char="r" char1="&quot;"/>
        <StringDetect attribute="String" context="TripleString" String="&quot;&quot;&quot;"/>
        <DetectChar attribute="String" context="String" char="&quot;"/>
        <RegExpr attribute="Declaration" context="#stay" String="\\b({words(CONTEXTUAL_DECL)})(?=\\s+[A-Za-z_])"/>
        <keyword attribute="Control Flow" context="#stay" String="control"/>
        <keyword attribute="Keyword" context="#stay" String="declarations"/>
        <keyword attribute="Operator" context="#stay" String="operator-words"/>
        <keyword attribute="Constant" context="#stay" String="constants"/>
        <keyword attribute="Special" context="#stay" String="special"/>
        <keyword attribute="Builtin" context="#stay" String="builtins"/>
        <RegExpr attribute="Number" context="#stay" String="{escape(number)}"/>
        <RegExpr attribute="Operator" context="#stay" String="{escape(OPERATOR_RE)}"/>
        <DetectChar attribute="Symbol" context="#stay" char="{{" beginRegion="Brace"/>
        <DetectChar attribute="Symbol" context="#stay" char="}}" endRegion="Brace"/>
        <AnyChar attribute="Symbol" context="#stay" String="()[],:;."/>
      </context>
      <context name="LineComment" attribute="Comment" lineEndContext="#pop">
        <DetectSpaces/>
        <IncludeRules context="##Comments"/>
      </context>
      <context name="BlockComment" attribute="Comment" lineEndContext="#stay">
        <Detect2Chars attribute="Comment" context="BlockComment" char="/" char1="*" beginRegion="Comment"/>
        <Detect2Chars attribute="Comment" context="#pop" char="*" char1="/" endRegion="Comment"/>
        <IncludeRules context="##Comments"/>
      </context>
      <context name="String" attribute="String" lineEndContext="#pop">
        <RegExpr attribute="Escape" context="#stay" String="{escape_rule}"/>
        <DetectChar attribute="Interpolation" context="Interpolation" char="{{"/>
        <DetectChar attribute="String" context="#pop" char="&quot;"/>
      </context>
      <context name="TripleString" attribute="String" lineEndContext="#stay">
        <RegExpr attribute="Escape" context="#stay" String="{escape_rule}"/>
        <DetectChar attribute="Interpolation" context="Interpolation" char="{{"/>
        <StringDetect attribute="String" context="#pop" String="&quot;&quot;&quot;"/>
      </context>
      <context name="RawString" attribute="String" lineEndContext="#pop">
        <DetectChar attribute="String" context="#pop" char="&quot;"/>
      </context>
      <context name="RawTripleString" attribute="String" lineEndContext="#stay">
        <StringDetect attribute="String" context="#pop" String="&quot;&quot;&quot;"/>
      </context>
      <context name="Interpolation" attribute="Normal Text" lineEndContext="#stay">
        <DetectChar attribute="Interpolation" context="#pop" char="}}"/>
        <IncludeRules context="Normal"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword" defStyleNum="dsKeyword"/>
      <itemData name="Control Flow" defStyleNum="dsControlFlow"/>
      <itemData name="Declaration" defStyleNum="dsKeyword"/>
      <itemData name="Operator" defStyleNum="dsOperator"/>
      <itemData name="Constant" defStyleNum="dsConstant"/>
      <itemData name="Special" defStyleNum="dsVariable"/>
      <itemData name="Builtin" defStyleNum="dsBuiltIn"/>
      <itemData name="Number" defStyleNum="dsDecVal"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Escape" defStyleNum="dsSpecialChar"/>
      <itemData name="Interpolation" defStyleNum="dsSpecialChar"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
      <itemData name="Symbol" defStyleNum="dsNormal"/>
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="//"/>
      <comment name="multiLine" start="/*" end="*/" region="Comment"/>
    </comments>
    <keywords casesensitive="1"/>
  </general>
</language>
"""


OUTPUTS: Dict[str, Callable[[], str]] = {
    "vscode-upsil/syntaxes/upsil.tmLanguage.json": textmate,
    "editor/upsil.lang": gtksourceview,
    "editor/upsil.xml": ksyntax,
}


def outdated() -> List[str]:
    """Output files whose contents differ from what the generator produces."""
    stale = []
    for rel, make in OUTPUTS.items():
        path = ROOT / rel
        if not path.exists() or path.read_text(encoding="utf-8") != make():
            stale.append(rel)
    return stale


def main(argv: List[str]) -> int:
    if "--check" in argv:
        stale = outdated()
        for rel in stale:
            print(f"out of date: {rel} (run python3 tools/gen_syntax.py)", file=sys.stderr)
        return 1 if stale else 0
    for rel, make in OUTPUTS.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make(), encoding="utf-8")
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
