# SPDX-License-Identifier: Apache-2.0
"""The compiler pipeline: source -> tokens -> tree -> checks -> Python ast -> code.

    >>> program = compile_source('print("hi")', "hello.upl")
    >>> exec(program.code, {"__name__": "__main__"})
    hi
"""

from __future__ import annotations

import ast
import linecache
import os
import warnings
from typing import Optional

from . import __version__
from .checker import Session, check
from .codegen import generate
from .lexer import normalize_source
from .parser import parse


class Program:
    """A compiled UpsiL program."""

    def __init__(self, code, tree: ast.Module, filename: str, source: str):
        self.code = code
        self.tree = tree
        self.filename = filename
        self.source = source

    def python_source(self) -> str:
        """Readable Python for ``upsil build``."""
        name = os.path.basename(self.filename)
        header = (f"# Generated by UpsiL {__version__} from {name}; edit the .upl file, not this one.\n"
                  f"# Running it needs the upsil package (pip install upsil).\n")
        return header + ast.unparse(self.tree) + "\n"


def register_source(filename: str, source: str) -> None:
    """Let tracebacks show UpsiL lines even for code that is not in a file."""
    from .tracebacks import UPSIL_FILES
    lines = source.splitlines(True)
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"
    linecache.cache[filename] = (len(source), None, lines, filename)
    UPSIL_FILES.add(filename)


def check_source(source: str, filename: str = "<input>", *, lint_types: bool = True,
                 session: Optional[Session] = None):
    """Parse and check without generating code (``upsil check``)."""
    source = normalize_source(source)
    module = parse(source, filename)
    return check(module, filename, source, lint_types=lint_types, session=session)


def compile_source(source: str, filename: str = "<input>", *, session: Optional[Session] = None,
                   repl: bool = False, lint_types: bool = False) -> Program:
    """Compile UpsiL source; raises ``upsil.errors.CompileError``."""
    source = normalize_source(source)
    module = parse(source, filename)
    result = check(module, filename, source, lint_types=lint_types, session=session)
    tree = generate(result, source, repl=repl)
    with warnings.catch_warnings():
        # CPython's hints about the generated code ("perhaps you missed a comma?") would
        # point at Python, not at UpsiL; the same mistakes fail clearly at run time.
        warnings.simplefilter("ignore", SyntaxWarning)
        code = compile(tree, filename, "exec", dont_inherit=True)
    register_source(filename, source)
    return Program(code, tree, filename, source)


def run_source(source: str, filename: str = "<input>", namespace: Optional[dict] = None) -> dict:
    """Compile and run; returns the program's global namespace."""
    program = compile_source(source, filename)
    ns = namespace if namespace is not None else {"__name__": "__main__"}
    ns.setdefault("__file__", filename)
    exec(program.code, ns)
    return ns
